### ISSUE TITLE
你好，这个DAG真实地址到底是哪个地址啊，我把所有找到的ip地址都试了一遍，还是提示我找不到文件下载失败，是我漏掉什么步骤了吗

### ISSUE THREAD

**Issue by superbottle** [shuoyuan/ChainsFL-implementation#2]
![M%E QQIBQ`~RO@UPO@T5EY9](https://user-images.githubusercontent.com/94426437/181070494-a82dc391-e6e2-454b-8db9-36d35d754f6a.png)

**Comment by shuoyuan** [comment]
`dict_users.pkl` 文件只是我实验用的字典，而这个文件应当没有保存到你的 IPFS 网络中，所以才会下载出错。
你注释 `./dagMainChain/clientRun.py` 的171-185行应当不影响使用。

**Comment by superbottle** [comment]
！谢谢！
