### ISSUE TITLE
不好意思，能问一下ipfs上面要下载的第一个pkl文件的事吗

### ISSUE THREAD

**Issue by superbottle** [shuoyuan/ChainsFL-implementation#3]
就是哈希值为QmTZqGKUEvD5F8vQyEEJLJB7rzX17tpnN2Uu4YWBRZEYQx的文件。
看了一下好像这个文件要从ipfs系统里面下载下来，但是好像文件丢失下载不到了。往ipfs里上传下载其他文件都是可以的。
还是说这个文件在别的地方我没找到，或者是要我自己弄一个呀。
![RY {A6UL_){ 7T WG@NHL1](https://user-images.githubusercontent.com/94426437/184493699-0755fe83-eb99-41b0-a3bd-a1889da88856.png)

**Comment by shuoyuan** [comment]
`QmTZqGKUEvD5F8vQyEEJLJB7rzX17tpnN2Uu4YWBRZEYQx` 是我本地实验的基础模型，并未上传到公网的IPFS。
可以使用 `./federatedLearning/buildModels.py` 中的 `modelBuild` 模块自行生成一个基础模型，并参照项目中的 `torch.save()` 样例保存成文件后上传到自建的IPFS网络。
另外，还需要将项目中的 `QmTZqGKUEvD5F8vQyEEJLJB7rzX17tpnN2Uu4YWBRZEYQx` 修改成相应的模型哈希值。
